//
//  RecipeViewModel.swift
//  RecipeApp
//
//  Created by Gabriele Esposito on 18/10/23.
//

import Foundation
import Observation

@Observable class RecipeViewModel{
    var recipe : [Recipe] = [
        
        //Italian recipes
        Recipe(name: "Pasta Aglio e Olio", time: "15-20 minutes", procedure: "Cook pasta, sauté minced garlic in olive oil, add red pepper flakes, toss with cooked pasta, and garnish with chopped parsley.", imageName: "Pasta Aglio e Olio", ingredients: "Spaghetti, garlic, olive oil, red pepper flakes, parsley, salt.", country: "Italy"),
        Recipe(name: "Caprese Salad", time: "10 minutes", procedure: "Slice tomatoes and mozzarella, arrange with fresh basil leaves, drizzle with olive oil and balsamic vinegar, and season with salt and pepper.", imageName: "Caprese Salad", ingredients: "Tomatoes, fresh mozzarella, fresh basil, olive oil, balsamic vinegar, salt, and pepper.", country: "Italy"),
        Recipe(name: "Bruschetta", time: "15-20 minutes", procedure: "Toast slices of baguette, rub with garlic, top with diced tomatoes, fresh basil, olive oil, and season with salt and pepper.", imageName: "Bruschetta", ingredients: "Baguette, tomatoes, garlic, fresh basil, olive oil, salt, and pepper.", country: "Italy"),
        Recipe(name: "Pasta with Pesto", time: "15-20 minutes", procedure: "Cook pasta, toss with pesto sauce, and sprinkle with Parmesan cheese.", imageName: "Pasta with Pesto", ingredients: "Pasta, pesto sauce, grated Parmesan cheese.", country: "Italy"),
        Recipe(name: "Frittata", time: "20-25 minutes", procedure: "Sauté vegetables, pour beaten eggs over them, cook until set, and season with salt and pepper.", imageName: "Frittata", ingredients: "Eggs, vegetables (e.g., bell peppers, onions, zucchini), olive oil, salt, and pepper.", country: "Italy"),
        Recipe(name: "Minestrone Soup", time: "30-40 minutes", procedure: "Combine pasta or rice, canned beans, canned tomatoes, mixed vegetables, vegetable broth, herbs, salt, and pepper. Simmer until vegetables are tender.", imageName: "Minestrone Soup", ingredients: "Pasta or rice, canned beans, canned tomatoes, mixed vegetables, vegetable broth, herbs, salt, and pepper.", country: "Italy"),
        Recipe(name: "Risotto", time: "25-30 minutes", procedure: "Sauté onions in butter, add rice, gradually stir in broth, and finish with Parmesan cheese.", imageName: "Risotto", ingredients: "Arborio rice, chicken or vegetable broth, onion, butter, Parmesan cheese, salt, and pepper.", country: "Italy"),
        Recipe(name: "Cacio e Pepe", time: "15-20 minutes", procedure: "Cook pasta, mix with grated Pecorino Romano and black pepper until creamy.", imageName: "Cacio e Pepe", ingredients: "Spaghetti, Pecorino Romano cheese, black pepper, salt.", country: "Italy"),
        Recipe(name: "Pasta Carbonara", time: "20-25 minutes", procedure: "Cook pasta, sauté pancetta, combine with beaten eggs, cheese, and black pepper.", imageName: "Pasta Carbonara", ingredients: "Spaghetti, eggs, grated Pecorino Romano cheese, pancetta or bacon, black pepper, salt.", country: "Italy"),
        Recipe(name: "Eggplant Parmesan", time: "45-50 minutes", procedure: "Bread and fry eggplant slices, layer with sauce and cheese, then bake until bubbly.", imageName: "Eggplant Parmesan", ingredients: "Eggplant, breadcrumbs, marinara sauce, mozzarella cheese, Parmesan cheese, and olive oil.", country: "Italy"),
        
        //Iranian recipes
        Recipe(name: "Chelo Kebab", time: "45-60 minutes", procedure: "Marinate and grill skewers of minced meat (koobideh) or chunks of meat (barg), serve with saffron-infused rice (chelo) and grilled tomatoes.", imageName: "Chelo Kebab", ingredients: "Ground meat or meat chunks, saffron, rice, tomatoes, onion, sumac, yogurt, salt, and pepper.", country: "Iran"),
        Recipe(name: "Ghormeh Sabzi", time: "2-2.5 hours", procedure: "Cook a stew of herbs (sabzi), red kidney beans, and chunks of meat (usually beef or lamb). Serve with rice.", imageName: "Ghormeh Sabzi", ingredients: "Herbs (parsley, cilantro, scallion, fenugreek), red kidney beans, beef or lamb, dried limes, turmeric, oil, salt, and pepper.", country: "Iran"),
        Recipe(name: "Tahchin", time: "1.5-2 hours", procedure: "Make a crispy rice cake layered with saffron-infused yogurt, marinated chicken, and barberries.", imageName: "Tahchin", ingredients: "Basmati rice, yogurt, chicken, saffron, barberries, eggs, oil, salt, and pepper.", country: "Iran"),
        Recipe(name: "Kashk-e Bademjan", time: "40-50 minutes", procedure: "Prepare an eggplant and walnut dip with a touch of whey (kashk). Serve with flatbread.", imageName: "Kashk-e Bademjan", ingredients: "Eggplants, walnuts, kashk, garlic, onions, mint, oil, salt, and pepper.", country: "Iran"),
        Recipe(name: "Zereshk Polo", time: "1.5-2 hours", procedure: "Make saffron-infused rice (polo) with barberries (zereshk) and serve with chicken.", imageName: "Zereshk Polo", ingredients: "Basmati rice, chicken, saffron, barberries, oil, sugar, salt, and pepper.", country: "Iran"),
        Recipe(name: "Ash-e Reshteh", time: "1.5-2 hours", procedure: "Cook a hearty noodle and herb soup with beans. Garnish with whey (kashk) and fried mint.", imageName: "Ash-e Reshteh", ingredients: "Noodles, herbs (spinach, parsley, dill), beans, kashk, garlic, onions, oil, salt, and pepper.", country: "Iran"),
        Recipe(name: "Mirza Ghasemi", time: "40-50 minutes", procedure: "Roast eggplants, peel and chop them. Cook with garlic, tomatoes, and beaten eggs. Serve with flatbread.", imageName: "Mirza Ghasemi", ingredients: "Eggplants, tomatoes, eggs, garlic, oil, salt, and pepper.", country: "Iran"),
        Recipe(name: "Dolmeh", time: "2-2.5 hours", procedure: "Stuffed grape leaves or vegetables with a mixture of rice, ground meat, and herbs. Cook with a tangy tomato sauce.", imageName: "Dolmeh", ingredients: "Grape leaves or vegetables (zucchini, bell peppers), rice, ground meat, herbs, tomatoes, lemon juice, oil, salt, and pepper.", country: "Iran"),
        Recipe(name: "Joojeh Kabab", time: "45-60 minutes", procedure: "Marinate and grill skewers of marinated chicken. Serve with saff", imageName: "Joojeh Kabab", ingredients: "Chicken Breast, Spices(zaffron)"),
        
        //Indian recipes
        Recipe(name: "Butter Chicken", time: "45-60 minutes", procedure: "Cook marinated chicken in a creamy tomato sauce with butter and spices. Serve with naan or rice.", imageName: "Butter Chicken", ingredients: "Chicken, tomatoes, butter, cream, garlic, ginger, spices, salt, and pepper.", country: "India"),
        Recipe(name: "Biryani", time: "1.5-2 hours", procedure: "Layer fragrant rice with marinated meat or vegetables. Cook with spices and garnish with fried onions and herbs.", imageName: "Biryani", ingredients: "Basmati rice, meat or vegetables, spices, onions, yogurt, mint, and coriander.", country: "India"),
        Recipe(name: "Paneer Tikka", time: "30-40 minutes", procedure: "Marinate paneer (Indian cottage cheese) and vegetables, then grill or roast until charred. Serve with mint chutney.", imageName: "Paneer Tikka", ingredients: "Paneer, bell peppers, onions, yogurt, spices, lemon juice, mint chutney.", country: "India"),
        Recipe(name: "Chana Masala", time: "40-50 minutes", procedure: "Cook chickpeas in a tomato-based gravy with spices. Serve with rice or flatbread.", imageName: "Chana Masala", ingredients: "Chickpeas, tomatoes, spices, onions, garlic, ginger, oil, and coriander.", country: "India"),
        Recipe(name: "Palak Paneer", time: "30-40 minutes", procedure: "Make a creamy spinach sauce and add paneer (cottage cheese). Serve with naan or rice.", imageName: "Palak Paneer", ingredients: "Paneer, spinach, cream, spices, garlic, ginger, ghee, and coriander.", country: "India"),
        Recipe(name: "Tandoori Chicken", time: "40-50 minutes", procedure: "Marinate chicken in yogurt and spices, then grill or roast until charred. Serve with naan and mint chutney.", imageName: "Tandoori Chicken", ingredients: "Chicken, yogurt, spices, lemon juice, mint chutney.", country: "India"),
        Recipe(name: "Dosa", time: "12-18 hours (includes soaking and fermentation)", procedure: "Prepare a thin, crispy fermented rice crepe. Serve with sambar and coconut chutney.", imageName: "Dosa", ingredients: "Rice and urad dal (black gram) for batter, spices, sambar, and coconut chutney.", country: "India"),
        Recipe(name: "Aloo Gobi", time: "30-40 minutes", procedure: "Cook potatoes and cauliflower in a spiced tomato gravy. Serve with rice or roti.", imageName: "Aloo Gobi", ingredients: "Potatoes, cauliflower, tomatoes, spices, onions, garlic, ginger, oil, and coriander.", country: "India"),
        Recipe(name: "Chicken Tikka Masala", time: "45-60 minutes", procedure: "Grill marinated chicken and simmer in a creamy tomato sauce with spices. Serve with rice or naan.", imageName: "Chicken Tikka Masala", ingredients: "Chicken, tomatoes, cream, yogurt, spices, garlic, ginger, ghee, and coriander.", country: "India"),
        Recipe(name: "Rogan Josh", time: "1.5-2 hours", procedure: "Cook tender pieces of meat in a rich, aromatic gravy. Serve with naan or rice.", imageName: "Rogan Josh", ingredients: "Meat (typically lamb), tomatoes, yogurt, spices, garlic, ginger, ghee, and coriander.", country: "India"),
        
        //Japanese recipes
        Recipe(name: "Sushi Rolls (Maki)", time: "30-45 minutes", procedure: "Prepare vinegared rice, place on a sheet of nori (seaweed), add ingredients like fish, vegetables, and avocado, then roll it up. Slice into bite-sized pieces.", imageName: "Sushi Rolls", ingredients: "Sushi rice, nori (seaweed), fish, vegetables, soy sauce, and wasabi.", country: "Japan"),
        Recipe(name: "Teriyaki Chicken", time: "30-40 minutes", procedure: "Cook chicken in a sweet and savory teriyaki sauce until caramelized. Serve with steamed rice and vegetables.", imageName: "Teriyaki Chicken", ingredients: "Chicken, soy sauce, sake, mirin, sugar, garlic, ginger, steamed rice.", country: "Japan"),
        Recipe(name: "Tempura", time: "20-30 minutes", procedure: "Dip vegetables or seafood in a light batter and deep-fry until crispy. Serve with a dipping sauce.", imageName: "Tempura", ingredients: "Vegetables or seafood, tempura batter, oil for frying, tempura dipping sauce.", country: "Japan"),
        Recipe(name: "Ramen", time: "1-1.5 hours", procedure: "Make a flavorful broth, cook noodles, and serve with various toppings like chashu pork, boiled eggs, and scallions.", imageName: "Ramen", ingredients: "Ramen noodles, pork or chicken broth, chashu pork, eggs, scallions, nori, and bamboo shoots.", country: "Japan"),
        Recipe(name: "Gyoza", time: "30-40 minutes", procedure: "Fill dumpling wrappers with a mixture of ground pork, cabbage, and seasonings, then pan-fry until crispy. Serve with dipping sauce.", imageName: "Gyoza", ingredients: "Ground pork, cabbage, garlic, ginger, gyoza wrappers, soy sauce, and vinegar.", country: "Japan"),
        Recipe(name: "Okonomiyaki", time: "30-40 minutes", procedure: "Make a savory pancake with cabbage and your choice of ingredients, then top with okonomi sauce, mayonnaise, and bonito flakes.", imageName: "Okonomiyaki", ingredients: "Cabbage, flour, eggs, dashi, okonomi sauce, mayonnaise, bonito flakes.", country: "Japan"),
        Recipe(name: "Katsu Curry", time: "45-60 minutes", procedure: "Bread and deep-fry breaded cutlets of meat (usually pork or chicken), serve with Japanese curry sauce, and rice.", imageName: "Katsu Curry", ingredients: "Meat cutlets, panko breadcrumbs, Japanese curry roux, rice.", country: "Japan"),
        Recipe(name: "Yakitori", time: "30-40 minutes", procedure: "Skewer and grill bite-sized pieces of chicken, vegetables, or other ingredients, then brush with a flavorful tare sauce.", imageName: "Yakitori", ingredients: "Chicken, vegetables, tare sauce, skewers.", country: "Japan"),
        Recipe(name: "Chirashi Sushi", time: "30-45 minutes", procedure: "Scatter a variety of sashimi, vegetables, and pickled ingredients over a bowl of sushi rice. Serve with soy sauce and wasabi.", imageName: "Chirashi Sushi", ingredients: "Sashimi, sushi rice, vegetables, soy sauce, wasabi.", country: "Japan"),
        Recipe(name: "Soba Noodles", time: "20-30 minutes", procedure: "Cook buckwheat soba noodles and serve them hot or cold with a dipping sauce or in a broth.", imageName: "Soba Noodles", ingredients: "Soba noodles, soba tsuyu (dipping sauce or broth), scallions, and wasabi.", country: "Japan"),
        
        //Norwegian recipes
        Recipe(name: "Potetballer (Potato Dumplings)", time: "30-40 minutes", procedure: "Make potato dumplings served with butter and lingonberry jam.", imageName: "Potetballer", ingredients: "Potatoes, flour, salt, butter, lingonberry jam.", country: "Norway"),
        Recipe(name: "Fiskekaker (Fish Cakes)", time: "30-40 minutes", procedure: "Prepare fish cakes with a mixture of fish, potatoes, and seasonings, pan-fry until golden brown.", imageName: "Fiskekaker", ingredients: "Fish, potatoes, onions, milk, flour, salt, pepper, butter.", country: "Norway"),
        Recipe(name: "Flatbrød (Norwegian Flatbread)", time: "30-40 minutes", procedure: "Bake thin, crispy flatbreads traditionally served with butter, cheese, or smoked salmon.", imageName: "Flatbrød", ingredients: "Flour, water, salt, butter, cheese, smoked salmon.", country: "Norway"),
        Recipe(name: "Fiskegrateng (Fish Gratin)", time: "30-40 minutes", procedure: "Prepare a fish gratin with a creamy sauce and top with breadcrumbs. Bake until golden and bubbly.", imageName: "Fiskegrateng", ingredients: "Fish, potatoes, white sauce, breadcrumbs, butter, parsley.", country: "Norway"),
        Recipe(name: "Rullekake (Swiss Roll Cake)", time: "30-40 minutes", procedure: "Make a sponge cake rolled with jam or cream filling, dusted with powdered sugar.", imageName: "Rullekake", ingredients: "Eggs, sugar, flour, jam or cream, powdered sugar.", country: "Norway"),
        Recipe(name: "Koldtbord", time: "Varies (buffet-style)", procedure: "Prepare a smorgasbord of cold dishes, including herring, cured meats, cheeses, salads, and bread.", imageName: "Koldtbord", ingredients: "Herring, cured meats, cheeses, salads, and bread.", country: "Norway"),
        Recipe(name: "Pølse med Lompe", time: "15-20 minutes", procedure: "Assemble hot dogs with a soft flatbread (lompe), sausage, and condiments like ketchup and mustard.", imageName: "Pølse med Lompe", ingredients: "Soft flatbread (lompe), sausages, ketchup, and mustard.", country: "Norway"),
        Recipe(name: "Rømmegrøt", time: "30-40 minutes", procedure: "Prepare a rich sour cream porridge, traditionally served with sugar, cinnamon, and butter.", imageName: "Rømmegrøt", ingredients: "Sour cream, flour, sugar, cinnamon, and butter.", country: "Norway"),
        Recipe(name: "Lefse", time: "30-40 minutes", procedure: "Make soft, Norwegian flatbreads often served with butter, sugar, and cinnamon.", imageName: "Lefse", ingredients: "Potatoes, flour, sugar, cinnamon, butter.", country: "Norway"),
        
        //French recipes
        Recipe(name: "Croque-Monsieur", time: "25 minutes", procedure: "Make a classic French grilled ham and cheese sandwich, topped with béchamel sauce and broiled until golden.", imageName: "Croque-Monsieur", ingredients: "Bread, ham, Gruyère cheese, butter, flour, milk, nutmeg.", country: "France"),
        Recipe(name: "Nicoise Salad", time: "20 minutes", procedure: "Assemble a salad with tuna, olives, hard-boiled eggs, tomatoes, and green beans, drizzled with vinaigrette.", imageName: "Nicoise Salad", ingredients: "Tuna, olives, eggs, tomatoes, green beans, vinaigrette.", country: "France"),
        Recipe(name: "Quiche Lorraine", time: "45 minutes", procedure: "Bake a savory tart with bacon and cheese in a pie crust.", imageName: "Quiche Lorraine", ingredients: "Pie crust, bacon, Gruyère cheese, eggs, cream, nutmeg.", country: "France"),
        Recipe(name: "French Onion Soup", time: "45 minutes", procedure: "Cook onions in butter until caramelized, then simmer with beef broth and top with toasted bread and melted cheese.", imageName: "French Onion Soup", ingredients: "Onions, butter, beef broth, bread, Gruyère cheese.", country: "France"),
        Recipe(name: "Salmon with Lemon-Dill Sauce", time: "30 minutes", procedure: "Pan-sear salmon and serve with a lemon-dill sauce, capers, and a side of vegetables.", imageName: "Salmon with Lemon-Dill Sauce", ingredients: "Salmon, lemon, dill, capers, vegetables.", country: "France"),
        Recipe(name: "Ratatouille", time: "30 minutes", procedure: "Sauté eggplant, zucchini, and bell peppers with herbs and tomatoes. Serve as a side or main dish.", imageName: "Ratatouille", ingredients: "Eggplant, zucchini, bell peppers, tomatoes, garlic, herbs.", country: "France"),
        Recipe(name: "Beef Bourguignon", time: "45 minutes", procedure: "Sauté beef with mushrooms and onions, then simmer in red wine for a quick version of this classic dish.", imageName: "Beef Bourguignon", ingredients: "Beef, mushrooms, onions, red wine, garlic, thyme.", country: "France"),
        Recipe(name: "Sole Meunière", time: "30 minutes", procedure: "Pan-fry sole in a browned butter sauce with lemon and parsley, for a simple and elegant dish.", imageName: "Sole Meunière", ingredients: "Sole, butter, lemon, parsley.", country: "France"),
        Recipe(name: "Chicken Fricassee", time: "45 minutes", procedure: "Cook chicken in a creamy white wine sauce with mushrooms and pearl onions.", imageName: "Chicken Fricassee", ingredients: "Chicken, white wine, mushrooms, pearl onions, cream.", country: "France"),
        Recipe(name: "Provencal Ratatouille", time: "40 minutes", procedure: "Sauté tomatoes, bell peppers, zucchini, and herbs for a traditional Provençal side dish.", imageName: "Provencal Ratatouille", ingredients: "Tomatoes, bell peppers, zucchini, garlic, herbs.", country: "France"),
        
        //Spanish recipes
        Recipe(name: "Paella", time: "45 minutes", procedure: "Cook a flavorful rice dish with saffron, seafood, and various meats in a wide, shallow pan.", imageName: "Paella", ingredients: "Rice, saffron, chicken, shrimp, mussels, bell peppers, onions, garlic.", country: "Spain"),
        Recipe(name: "Gazpacho", time: "15 minutes", procedure: "Blend ripe tomatoes, cucumbers, bell peppers, and garlic for a refreshing cold soup.", imageName: "Gazpacho", ingredients: "Tomatoes, cucumbers, bell peppers, garlic, olive oil, vinegar.", country: "Spain"),
        Recipe(name: "Tortilla Española", time: "30 minutes", procedure: "Make a classic Spanish omelette with eggs, potatoes, and onions. Served in wedges.", imageName: "Tortilla Española", ingredients: "Eggs, potatoes, onions, olive oil.", country: "Spain"),
        Recipe(name: "Patatas Bravas", time: "30 minutes", procedure: "Fry cubed potatoes and serve with a spicy tomato sauce and garlic aioli.", imageName: "Patatas Bravas", ingredients: "Potatoes, tomato sauce, paprika, garlic, mayonnaise.", country: "Spain"),
        Recipe(name: "Sangria", time: "10 minutes", procedure: "Prepare a refreshing Spanish drink with red wine, fruit, and a touch of brandy.", imageName: "Sangria", ingredients: "Red wine, oranges, lemons, brandy, sugar.", country: "Spain"),
        Recipe(name: "Pulpo a la Gallega", time: "35 minutes", procedure: "Boil octopus and slice it, then serve with paprika, olive oil, and potatoes.", imageName: "Pulpo a la Gallega", ingredients: "Octopus, paprika, olive oil, potatoes.", country: "Spain"),
        Recipe(name: "Churros", time: "30 minutes", procedure: "Make crispy fried dough, dusted with sugar, served with a cup of thick hot chocolate.", imageName: "Churros", ingredients: "Flour, sugar, water, salt, chocolate.", country: "Spain"),
        Recipe(name: "Albondigas", time: "35 minutes", procedure: "Prepare Spanish meatballs in a tomato sauce with a blend of spices.", imageName: "Albondigas", ingredients: "Ground beef, breadcrumbs, garlic, paprika, tomatoes.", country: "Spain"),
        Recipe(name: "Spanish Flan", time: "50 minutes", procedure: "Bake a creamy caramel custard dessert in a water bath until set.", imageName: "Spanish Flan", ingredients: "Eggs, milk, sugar, vanilla, caramel sauce.", country: "Spain"),
        Recipe(name: "Escalivada", time: "45 minutes", procedure: "Roast bell peppers, eggplant, and onions, then serve with olive oil and herbs.", imageName: "Escalivada", ingredients: "Bell peppers, eggplant, onions, olive oil, herbs.", country: "Spain"),
        
        //Chinese recipes
        Recipe(name: "Kung Pao Chicken", time: "30 minutes", procedure: "Stir-fry chicken with peanuts, vegetables, and a spicy sauce. Garnish with green onions.", imageName: "Kung Pao Chicken", ingredients: "Chicken, peanuts, bell peppers, dried red chilies, ginger, soy sauce.", country: "China"),
        Recipe(name: "Egg Fried Rice", time: "20 minutes", procedure: "Cook rice with scrambled eggs, vegetables, and soy sauce for a quick and tasty dish.", imageName: "Egg Fried Rice", ingredients: "Rice, eggs, peas, carrots, soy sauce.", country: "China"),
        Recipe(name: "Hot and Sour Soup", time: "30 minutes", procedure: "Prepare a savory soup with mushrooms, tofu, bamboo shoots, and a tangy broth.", imageName: "Hot and Sour Soup", ingredients: "Mushrooms, tofu, bamboo shoots, vinegar, soy sauce.", country: "China"),
        Recipe(name: "Mongolian Beef", time: "25 minutes", procedure: "Stir-fry beef with scallions, garlic, and a sweet soy-based sauce. Serve over rice.", imageName: "Mongolian Beef", ingredients: "Beef, scallions, garlic, soy sauce, sugar, hoisin sauce.", country: "China"),
        Recipe(name: "Dim Sum (Steamed Dumplings)", time: "40 minutes", procedure: "Make steamed dumplings filled with various fillings, such as pork and shrimp.", imageName: "Dim Sum", ingredients: "Ground pork, shrimp, dumpling wrappers.", country: "China"),
        Recipe(name: "Sweet and Sour Chicken", time: "35 minutes", procedure: "Coat chicken in a sweet and tangy sauce, with bell peppers and pineapple.", imageName: "Sweet and Sour Chicken", ingredients: "Chicken, bell peppers, pineapple, vinegar, ketchup.", country: "China"),
        Recipe(name: "Spring Rolls", time: "30 minutes", procedure: "Roll a mixture of vegetables, shrimp, and pork in rice paper wrappers. Serve with dipping sauce.", imageName: "Spring Rolls", ingredients: "Shrimp, pork, rice paper, vegetables, hoisin sauce.", country: "China"),
        Recipe(name: "Mapo Tofu", time: "25 minutes", procedure: "Cook tofu in a spicy and numbing sauce with ground pork and Sichuan peppercorns.", imageName: "Mapo Tofu", ingredients: "Tofu, ground pork, Sichuan peppercorns, chili bean paste.", country: "China"),
        Recipe(name: "Szechuan Chicken", time: "30 minutes", procedure: "Stir-fry chicken with vegetables in a spicy Szechuan sauce. Serve with rice.", imageName: "Szechuan Chicken", ingredients: "Chicken, vegetables, ginger, garlic, soy sauce, chili paste.", country: "China"),
        Recipe(name: "General Tso's Chicken", time: "35 minutes", procedure: "Coat chicken in a sweet and slightly spicy sauce. Garnish with scallions.", imageName: "General Tso's Chicken", ingredients: "Chicken, scallions, ginger, garlic, soy sauce, sugar.", country: "China"),
        
        //US recipes
        Recipe(name: "Grilled Cheese Sandwich", time: "15 minutes", procedure: "Make a simple sandwich with melted cheese between two slices of bread, cooked on a griddle or in a pan.", imageName: "Grilled Cheese Sandwich", ingredients: "Bread, cheese, butter.", country: "United States"),
        Recipe(name: "BLT Sandwich", time: "20 minutes", procedure: "Assemble a sandwich with crispy bacon, lettuce, tomato, and mayonnaise.", imageName: "BLT Sandwich", ingredients: "Bread, bacon, lettuce, tomato, mayonnaise.", country: "United States"),
        Recipe(name: "Tuna Salad", time: "20 minutes", procedure: "Mix canned tuna with mayonnaise, celery, onions, and seasonings. Serve as a sandwich or on a bed of lettuce.", imageName: "Tuna Salad", ingredients: "Canned tuna, mayonnaise, celery, onions, lettuce.", country: "United States"),
        Recipe(name: "Baked Potato with Sour Cream and Chives", time: "30 minutes", procedure: "Bake potatoes until tender, then top with sour cream, chives, and your choice of additional toppings like cheese or bacon.", imageName: "Baked Potato", ingredients: "Potatoes, sour cream, chives, cheese (optional), bacon (optional).", country: "United States"),
        Recipe(name: "Fajitas", time: "30 minutes", procedure: "Sauté strips of chicken or beef with bell peppers and onions. Serve with tortillas and toppings like sour cream and salsa.", imageName: "Fajitas", ingredients: "Chicken or beef, bell peppers, onions, tortillas, sour cream, salsa.", country: "United States"),
        Recipe(name: "Cobb Salad", time: "25 minutes", procedure: "Arrange lettuce, tomatoes, bacon, hard-boiled eggs, avocado, and blue cheese in rows. Drizzle with dressing.", imageName: "Cobb Salad", ingredients: "Lettuce, tomatoes, bacon, eggs, avocado, blue cheese, dressing.", country: "United States"),
        Recipe(name: "Shrimp Scampi", time: "25 minutes", procedure: "Sauté shrimp in garlic and butter, then add lemon juice and white wine. Serve over cooked linguine.", imageName: "Shrimp Scampi", ingredients: "Shrimp, garlic, butter, lemon juice, white wine, linguine.", country: "United States"),
        Recipe(name: "Chili Dogs", time: "30 minutes", procedure: "Cook hot dogs and top with homemade chili, onions, and cheese. Serve in buns.", imageName: "Chili Dogs", ingredients: "Hot dogs, chili, onions, cheese, buns.", country: "United States"),
        Recipe(name: "Pulled Pork Sandwiches", time: "40 minutes", procedure: "Slow-cook pork with barbecue sauce, then shred and serve on buns with coleslaw.", imageName: "Pulled Pork Sandwiches", ingredients: "Pork, barbecue sauce, buns, coleslaw.", country: "United States"),
        Recipe(name: "Chicken and Broccoli Alfredo", time: "30 minutes", procedure: "Sauté chicken and broccoli, then toss with Alfredo sauce and cooked fettuccine.", imageName: "Chicken and Broccoli Alfredo", ingredients: "Chicken, broccoli, Alfredo sauce, fettuccine.", country: "United States")
    ]
    
    var country: String = "Italy"
    var name : String = ""
}

var datas = RecipeViewModel()
